name: Deploy Terraform to HCP

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  HCP_TERRAFORM_ORG: enpicie
  HCP_TERRAFORM_WORKSPACE: hcp-tf-aws-lambda-apigw-role

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform and Deploy via HCP Terraform
        uses: chzylee/action-workflow-hcp-terraform@v1.0.2
        with:
          tfcode_path: . # Action run from context of the repository root
          tfc_hostname: app.terraform.io # HCP Terraform Cloud URL
          tfc_organization: ${{ env.HCP_TERRAFORM_ORG }}
          tfc_workspace: ${{ env.HCP_TERRAFORM_WORKSPACE }}
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
